### ISSUE TITLE
Two errors in this sentence

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/react-update-lifecycle-readme#2]
Need to remove the apostrophe from this sentence, and remove the standalone "a" a few words later:
"That means whenever the component is receiving new props from it's parent or a the component state has changed."

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

This sentence has been rewritten based on your feedback. Thank you for this contribution!
