### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/react-update-lifecycle-readme#5]
This method can also be used to interact with the DOM, say be adjusting scroll position. 
This method can also be used to interact with the DOM, say **by** adjusting scroll position. 

This method is for deriving state, meaning you want to modify a components state based on something in the new props. 
This method is for deriving state, meaning you want to modify a **component's** state based on something in the new props.

**Comment by maxwellbenton** [comment]
Hi @arianaberger,

These sentences have been rewritten based on your feedback. Thank you for this contribution!
