### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by mcummings128** [learn-co-curriculum/react-update-lifecycle-readme#6]
In the getDerivedStateFromProps paragraphs:

Current: _This method is called on every update. That means whenever the component is receiving new props from it's parent or a the component state has changed._
Corrected: This method is called on every update, **meaning** whenever the component is receiving new props from **its** parent or **the** **component's** state has changed.

Current: _This method is for deriving state, meaning you want to modify a components state based on something in the new props._
Corrected: This method is for deriving state, meaning you want to modify a **component's** state based on something in the new props.

**Comment by maxwellbenton** [comment]
Hi @TimeSmash,

This sentences have been rewritten based on your feedback. Thank you for this contribution!
