### ISSUE TITLE
Render in wrong place on ordered list?

### ISSUE THREAD

**Issue by brandonbrown4792** [learn-co-curriculum/react-update-lifecycle-readme#7]
Paragraph 3 of the overview states that render is called just before componentDidUpdate, however, the ordered list shows render getting called just before getSnapshotBeforeUpdate.

**Comment by Sdcrouse** [comment]
`render` is in the right place on the ordered list. Check out the diagram from one of the previous lessons: https://github.com/learn-co-curriculum/react-component-lifecycle-overview

I think Paragraph 3 needs to be changed to this: "These methods always get called in the same order, and the `render()` method, which renders the React component into the DOM, will be called just before `getSnapshotBeforeUpdate`..."
